### ISSUE TITLE
TypeError: Cannot destructure property `bundleUrl` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by chenshuiluke** [alidcastano/rogue.js#52]
Hey, I've been checking out your project and I've been having some trouble integrating it into my React application which needs SSR. Essentially what happens is that I get the following error when I run `npm run dev`:

```
C:\Users\lukec\Documents\git\the-jade-podium\node_modules\@roguejs\app\dist\server.js:165
    constructor(App, { bundleUrl }) {
               ^
TypeError: Cannot destructure property `bundleUrl` of 'undefined' or 'null'.
    at new App (C:\Users\lukec\Documents\git\the-jade-podium\node_modules\@roguejs\app\dist\server.js:165:16)
    at Module../src/server.js (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\src\server.js:9:1)
    at __webpack_require__ (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:682:1)
    at fn (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:59:1)
    at Module../src/index.js (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\src\index.js:1:1)
    at __webpack_require__ (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:682:1)
    at fn (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:59:1)
    at Object.0 (C:\Users\lukec\Documents\git\the-jade-podium\build\server.js:1704:18)
    at __webpack_require__ (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:682:1)
    at module.exports../build/assets.json.module.exports.client.js (C:\Users\lukec\Documents\git\the-jade-podium\build\webpack:\webpack\bootstrap:749:1)
```
I modified my code to be similar to what you have for the with-razzle example. Here is my package.json:

```
{
  "name": "the-jade-podium",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@roguejs/app": "^0.6.8",
    "razzle": "^2.2.0",
    "react-bulma-components": "^1.5.0",
    "react-typography": "^0.16.13",
    "typeface-cabin-condensed": "0.0.54",
    "typeface-patua-one": "0.0.54",
    "typography": "^0.16.17",
    "typography-theme-funston": "^0.15.10",
    "babel-polyfill": "^6.26.0"
  },
  "scripts": {
    "dev": "razzle start"
  }
}
```

client.js

```
import { hydrate } from '@roguejs/app'
import App from './App'

hydrate(App)
```

index.js

```
import http from 'http'
import app from './server'

const server = http.createServer(app.render)

let currentApp = app

server.listen(process.env.PORT || 3000, error => {
  if (error) {
    console.log(error)
  }

  console.log('🚀 started')
})

if (module.hot) {
  console.log('✅  Server-side HMR Enabled!')

  module.hot.accept('./server', () => {
    console.log('🔁  HMR Reloading `./server`...')
    server.removeListener('request', currentApp)
    const newApp = require('./server').default
    server.on('request', newApp)
    currentApp = newApp
  })
}
```

server.js

```

import Rogue from '@roguejs/app/server'
import { Helmet } from 'react-helmet'
import serveStatic from 'serve-static'
import App from './App'

const publicDir = process.env.RAZZLE_PUBLIC_DIR
const bundleUrl = require(process.env.RAZZLE_ASSETS_MANIFEST).client.js

const app = new Rogue({
  Helmet,
  App, 
  bundleUrl
})

app.preuse(serveStatic(publicDir))

export default app

```

and my App.js

```
import React, { Component } from 'react';
import './App.css';
import 'react-bulma-components/dist/react-bulma-components.min.css';
import { Columns } from 'react-bulma-components';
import NavBar from './components/NavBar';
import Banner from './components/Banner';
import Typography from 'typography';
import funstonTheme from 'typography-theme-funston';
import logo from './assets/images/logo.png';

const typography = new Typography(funstonTheme);


typography.injectStyles();
class App extends Component {
  render() {
    return (
      <div className="App">
        <NavBar/>
        <Banner/>
      </div>
    );
  }
}

export default App;
```

Do you have any idea what I could be doing wrong?

**Comment by chenshuiluke** [comment]
Thanks man, I really appreciate you and your project
